const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  CREATE_CLIENTE: "CREATE_CLIENTE",
  GET_ALL_CLIENTES: "GET_ALL_CLIENTES",
  GET_CLIENTE: "GET_CLIENTE",
  DELETE_CLIENTE: "DELETE_CLIENTE",
  UPDATE_CLIENTE: "UPDATE_CLIENTE",
};

export default ACTIONS;
